### ISSUE TITLE
does not work :(

### ISSUE THREAD

**Issue by hayderux** [scvax/flutter-desktop#1]
ERROR: The process "launcher.exe" not found.

and black screen
![Screenshot (27)](https://user-images.githubusercontent.com/10659891/54086144-8b4ff680-4357-11e9-96e2-ed168f3f38ce.png)

**Comment by difaananda40** [comment]
yeah, same problem

**Comment by difaananda40** [comment]
up

**Comment by scvax** [comment]
Excuse me, I have been waiting for you. Can I look at the directory where the launcher.exe is located?

**Comment by scvax** [comment]
The above information comes from google translation

**Comment by scvax** [comment]
> ERROR: The process "launcher.exe" not found.
> 
> and black screen
> ![Screenshot (27)](https://user-images.githubusercontent.com/10659891/54086144-8b4ff680-4357-11e9-96e2-ed168f3f38ce.png)

ERROR: The process "launcher.exe" not found. This is normal. In order to close the previous window and reopen a window, for the white screen, check if the main method specifies the target platform.

**Comment by GerardusOrdo** [comment]
what version of flutter did you use? can you recompile your go flutter desktop embedder with newest version of flutter?

**Comment by scvax** [comment]
> what version of flutter did you use? can you recompile your go flutter desktop embedder with newest version of flutter?

Sorry, I don't need the new version of flutter now. but you can try replace "flutter_engine.dll" to new version.

**Comment by scvax** [comment]
Close. it work good in my computer.
